config/routes.rb
Rails.application.routes.draw do
  resources :loans do
    member do
      post 'return_loan'
      get 'confirm_return'
      post 'complete_return_loan'
    end
  end

  resources :students
  resources :books
  get 'welcome/index'
  root to: 'welcome#index'
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :email)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-4 mb-4">
      <h2 class="text-red-800 font-semibold"><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul class="list-disc ml-8">
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-end">
    <%= form.submit "Save", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full cursor-pointer" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="max-w-md mx-auto my-8 p-6 bg-white rounded-lg shadow-lg">
  <h1 class="text-2xl font-bold mb-4">
    <div class="bg-blue-500 text-white p-4">
        Editing Student
    <div>
</h1>

  <%= render 'form', student: @student %>
    <div class="w-full flex justify-between">
        <%= link_to 'Show', @student, class: "mt-4 text-sm text-gray-700 hover:underline" %>
        <%= link_to 'Back', students_path, class: "mt-4 text-sm text-gray-700 hover:underline" %>
    </div>
</div>

app/views/students/index.html.erb
<div class="p-4">
  <% if notice.present? %>
    <p id="notice" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-4"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-bold">Students</h1>
    <%= link_to 'New Student', new_student_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
  </div>

  <table class="w-full table-auto mb-4">
    <thead class="bg-gray-200 text-justify">
      <tr>
        <th class="py-2 px-4 border-b">Name</th>
        <th class="py-2 px-4 border-b">Email</th>
        <th class="py-2 px-4 border-b">Commands</th>
      </tr>
    </thead>

    <tbody class="text-justify">
      <% @students.each do |student| %>
        <tr class="h-8 hover:bg-gray-100 border-b">
          <td class="px-4 h-full"><%= student.name %></td>
          <td class="px-4 h-full"><%= student.email %></td>
          <td class="px-4 flex justify-start items-center h-8 gap-x-4">
            <%= link_to student, class: "hover:bg-blue-500 py-1 px-1 rounded cursor-pointer parent-hover-invert", title: "Show" do %>
              <%= image_tag("icons/eye.svg", alt: "Eye Icon") %>
            <% end %>
            <%= link_to edit_student_path(student), class: "hover:bg-green-500 py-1 px-1 rounded cursor-pointer parent-hover-invert", title: "Edit" do %>
              <%= image_tag("icons/pen.svg", alt: "Pen Icon") %>
            <% end %>
            <%= link_to student, class: "hover:bg-red-500 py-1 px-1 rounded cursor-pointer parent-hover-invert", method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" do %>
              <%= image_tag("icons/trash.svg", alt: "trash Icon") %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<div class="max-w-md mx-auto my-8 p-6 bg-white rounded-lg shadow-lg">
  <h1 class="text-2xl font-bold mb-4">
    <div class="bg-blue-500 text-white p-4">
        New Student
    <div>
  </h1>

  <%= render 'form', student: @student %>
    <div class="w-full flex justify-end">
        <%= link_to 'Back', students_path, class: "mt-4 text-sm text-gray-700 hover:underline" %>
    </div>
</div>

app/views/students/show.html.erb
<div class="max-w-md mx-auto my-8 p-6 bg-white rounded-lg shadow-lg">
  <% if notice.present? %>
    <p id="notice" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-4"><%= notice %></p>
  <% end %>

  <p class="mb-2">
    <strong class="text-gray-700">Name:</strong>
    <%= @student.name %>
  </p>

  <p class="mb-2">
    <strong class="text-gray-700">Email:</strong>
    <%= @student.email %>
  </p>

  <div class="flex">
    <%= link_to 'Edit', edit_student_path(@student), class: "mr-4 text-blue-500 hover:underline" %>
    <%= link_to 'Back', students_path, class: "text-gray-700 hover:underline" %>
  </div>
</div>